### ISSUE TITLE
File upload Widget link doesn't download file

### ISSUE THREAD

**Issue by extrajoss** [boscoh/plasticgui#1]
So I uploaded a file using the upload widget on the base page. 
The file uploaded correctly to 
/Users/xxxxxx/Code/Repos/plasticgui-master/nodeserver/files/1523343324017/readme.md

and produced a link on the webpage below the upload widget:
http://localhost:3000/file/1523343324017/readme.md

When I click the link it just opens the page 
http://localhost:3000

no file is downloaded or viewed. Not sure why. Looks like static files is pointed to the right spot?
```
// Load static files
app.use('/file', express.static('files'))
```

Also file upload only works the first 2 times, after that I get an error message like the below:

> Error: ENOENT: no such file or directory, rename '/Users/xxxxxx/Code/Repos/plasticgui-master/nodeserver/files/3e5289ff07bcb6ece68238de96eb2ec2' -> '/Users/xxxxxx/Code/Repos/plasticgui-master/nodeserver/files/1523343987709/readme.md'

the file '/Users/xxxxxx/Code/Repos/plasticgui-master/nodeserver/files/3e5289ff07bcb6ece68238de96eb2ec2' does exist though with permissions -rw-r--r--

If I restart the server I can then upload twice more before I start getting the ENOENT error again.

Any ideas?

**Comment by boscoh** [comment]
Fixed in commit https://github.com/boscoh/plasticgui/commit/f229d31f19763a06944af3266900fe70fdaf961a. It was due to inadvertently calling an async directory creation call, which should have been sync.
